language: elixir
elixir:
  - 1.2.6
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.0
otp_release:
  - 18.3
  - 19.3
  - 20.3
  - 21.0
matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.0
    - elixir: 1.3.4
      otp_release: 21.0
    - elixir: 1.4.5
      otp_release: 21.0
    - elixir: 1.5.3
      otp_release: 21.0
    - elixir: 1.6.6
      otp_release: 18.3
    - elixir: 1.7.0
      otp_release: 18.3
    - elixir: 1.7.0
      otp_release: 19.3
before_script: MIX_ENV=test mix compile --warnings-as-errors
script: mix coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
cache:
  directories:
    - _build
