language: elixir
elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.0
otp_release:
  - 19.3
  - 20.3
  - 21.2
matrix:
  exclude:
    - elixir: 1.8.0
      otp_release: 19.3
before_script: MIX_ENV=test mix compile --warnings-as-errors
script:
  - mix dialyzer --halt-exit-status --format simple
  - mix coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
cache:
  directories:
    - _build
